backend:
  name: git-gateway
  branch: main # 根据您的分支名称调整，可能是master或main

media_folder: "images/uploads" # 媒体文件将存储在网站的哪个目录
public_folder: "/images/uploads" # 上传的媒体文件的公共访问路径

collections:
  - name: "news" # 用于网址路由，如 /admin/collections/news
    label: "新闻" # 在UI中显示的名称
    folder: "_news" # 存储内容的文件夹
    create: true # 允许用户创建新文件
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # 文件名模板
    fields: # 字段，即内容的属性
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "概要", name: "description", widget: "text" }
      - { label: "内容", name: "body", widget: "markdown" }
      - { label: "缩略图", name: "thumbnail", widget: "image", required: false }

  - name: "members"
    label: "团队成员"
    folder: "_members"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "姓名", name: "name", widget: "string" }
      - { label: "职位", name: "position", widget: "string" }
      - { label: "照片", name: "photo", widget: "image", required: false }
      - { label: "简介", name: "bio", widget: "markdown" }
      - { label: "显示顺序", name: "order", widget: "number" }

  - name: "publications"
    label: "论文发表"
    folder: "_publications"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "作者", name: "authors", widget: "string" }
      - { label: "发表日期", name: "date", widget: "datetime" }
      - { label: "期刊/会议", name: "journal", widget: "string" }
      - { label: "摘要", name: "abstract", widget: "text", required: false }
      - { label: "链接", name: "link", widget: "string", required: false }
      - { label: "PDF文件", name: "pdf", widget: "file", required: false }

  - name: "pages"
    label: "页面"
    files:
      - file: "index.html"
        label: "首页"
        name: "home"
        fields:
          - { label: "标题", name: "title", widget: "string" }
          - { label: "描述", name: "description", widget: "text" }
          - {
              label: "背景图",
              name: "background_image",
              widget: "image",
              required: false,
            }
          - { label: "内容", name: "body", widget: "markdown" }

      - file: "contact.html"
        label: "联系我们"
        name: "contact"
        fields:
          - { label: "标题", name: "title", widget: "string" }
          - { label: "地址", name: "address", widget: "string" }
          - { label: "电话", name: "phone", widget: "string" }
          - { label: "邮箱", name: "email", widget: "string" }
          - { label: "内容", name: "body", widget: "markdown" }
